from typing import Optional
from pydantic import BaseModel, Field
from datetime import datetime

class Token(BaseModel):
    access_token: str = Field(
        ...,
        description="Access token string generated by encoding the payload"
    )
    token_type: str = Field(
        default="bearer",
        description="The access token type"
    )

class TokenPayload(BaseModel):
    sub: Optional[str] = Field(
        default=None,
        description="Suject i.e. user id"
    )
    exp: Optional[datetime] = Field(
        default=None,
        description="Expiration timestamp"
    )